# Generated by Django 4.2.16 on 2024-11-26 21:14

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "inserted_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "update_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("end_timestamp", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=63)),
                ("dob", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("phone_no", models.CharField(max_length=15)),
                ("address", models.CharField(max_length=1023)),
                ("pin_code", models.CharField(max_length=6)),
                ("status", models.CharField(max_length=5)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
